tcellmatch:
        conda: epytope_tf20
        options: 
                model: 
                        LSTM_CV0: iedb_BILSTM_CONCAT_LEARN_1_1_1_1_1_s_bilstm_cv0
                        LSTM_CV1: iedb_BILSTM_CONCAT_LEARN_1_1_1_1_1_s_bilstm_cv1
                        LSTM_CV2: iedb_BILSTM_CONCAT_LEARN_1_1_1_1_1_s_bilstm_cv2
                        GRU_CV0: iedb_BIGRU_CONCAT_BLOSUM_1_1_1_2_1_s_bigru_cv0
                        GRU_CV1: iedb_BIGRU_CONCAT_BLOSUM_1_1_1_2_1_s_bigru_cv1
                        GRU_CV2: iedb_BIGRU_CONCAT_BLOSUM_1_1_1_2_1_s_bigru_cv2
                        GRU_SEP_CV0: iedb_BIGRU_SEPARATE_BLOSUM_1_1_1_1_1_s_bigru_separate_cv0
                        GRU_SEP_CV1: iedb_BIGRU_SEPARATE_BLOSUM_1_1_1_1_1_s_bigru_separate_cv1
                        GRU_SEP_CV2: iedb_BIGRU_SEPARATE_BLOSUM_1_1_1_1_1_s_bigru_separate_cv2
                        LSTM_SEP_CV0: iedb_BILSTM_SEPARATE_BLOSUM_1_1_1_1_1_s_bilstm_separate_cv0
                        LSTM_SEP_CV1: iedb_BILSTM_SEPARATE_BLOSUM_1_1_1_1_1_s_bilstm_separate_cv1
                        LSTM_SEP_CV2: iedb_BILSTM_SEPARATE_BLOSUM_1_1_1_1_1_s_bilstm_separate_cv2
                        LINEAR_CV0: iedb_LINEAR_CONCAT_BLOSUM_1_1_1_1_1_s_linear_cv0
                        LINEAR_CV1: iedb_LINEAR_CONCAT_BLOSUM_1_1_1_1_1_s_linear_cv1
                        LINEAR_CV2: iedb_LINEAR_CONCAT_BLOSUM_1_1_1_1_1_s_linear_cv2

ergo-i:
        repository: ${PATH_EPYTOPE}/external/ERGO
        conda: epytope_torch11
        options: 
                model:
                        AE_VDJDB: ae_vdjdb1
                        LSTM_VDJDB: lstm_vdjdb1
                        AE_MCPAS: ae_mcpas1
                        LSTM_MCPAS: lstm_mcpas1

ergo-ii:
        repository: ${PATH_EPYTOPE}/external/ERGO-II
        conda: epytope_torch11
        options:
                dataset:
                        VDJDB: vdjdb
                        MCPAS: mcpas
         
imrex:
        conda: epytope_tf21
        options:
                model:
                        DOWNSAMPLED: 2020-07-24_19-18-39_trbmhcidown-shuffle-padded-b32-lre4-reg001/2020-07-24_19-18-39_trbmhcidown-shuffle-padded-b32-lre4-reg001.h5
                        FULL: 2020-07-30_11-30-27_trbmhci-shuffle-padded-b32-lre4-reg001/2020-07-30_11-30-27_trbmhci-shuffle-padded-b32-lre4-reg001.h5 

teinet:
        repository: ${PATH_EPYTOPE}/external/TEINet
        conda: epytope_torch11
        options:
                model:
                        LARGE_DS: ${PATH_EPYTOPE}/external/TEINet/models/large_dset.pth
                        SMALL_DS: ${PATH_EPYTOPE}/external/TEINet/models/teinet_data.pth

epitcr:
        repository: ${PATH_EPYTOPE}/external/epiTCR
        conda: epytope_torch10
        options:
                model:
                        WITH_MHC: rdforestWithMHCModel
                        WO_MHC: rdforestWithoutMHCModel
                        WO_MHC_NO_OVERLAP: rdforestWithoutMHCNonOverlapingModel

dlptcr:
        repository: ${PATH_EPYTOPE}/external/DLpTCR
        conda: epytope_tf21
        options:
                model_type:
                        ALPHA_BETA: AB 
                        ALPHA: A
                        BETA: B

attntap:
        repository: ${PATH_EPYTOPE}/external/AttnTAP
        conda: epytope_torch11
        options:
                model:
                        MCPAS: cv_model_0_mcpas_0
                        VDJDB: cv_model_0_vdjdb_0

