mixtcrpred: 
        repository: /external/MixTCRpred
        conda: epytope_torch21
nettcr-cat:
        repository: /external/NetTCR-2.2
        conda: epytope_torch21
        options:
                model_type:
                        pretrained: pretrained
                        peptide: peptide
                model:
                        t.0.v.1: t.0.v.1
                        t.0.v.2: t.0.v.2
                        t.0.v.3: t.0.v.3
                        t.0.v.4: t.0.v.4
                        t.1.v.0: t.1.v.0
                        t.1.v.2: t.1.v.2
                        t.1.v.3: t.1.v.3
                        t.1.v.4: t.1.v.4
                        t.2.v.0: t.2.v.0
                        t.2.v.1: t.2.v.1
                        t.2.v.3: t.2.v.3
                        t.2.v.4: t.2.v.4
                        t.3.v.0: t.3.v.0
                        t.3.v.1: t.3.v.1
                        t.3.v.2: t.3.v.2
                        t.3.v.4: t.3.v.4
                        t.4.v.0: t.4.v.0
                        t.4.v.1: t.4.v.1
                        t.4.v.2: t.4.v.2
                        t.4.v.3: t.4.v.3
tcrgp:
        repository: /external/TCRGP
        conda: epytope_tcrgp
